// Greybox map "de_douglas" — Phase 3. Layout data lives in
// assets/maps/de_douglas.json (single source of truth) so the same numbers
// drive BOTH the Rapier cuboid colliders (here) and the Blender render/lightmap
// bake (tools/blender/build_map.py). Coords: three.js metres, Y up, floor top
// at y=0. Everything on a 0.5 m grid.
//
// A capital "D" on its back: a straight WEST spine wall closed by a half-ellipse
// CURVE bulging EAST. T and CT spawn behind walls at the two ends of the spine;
// the spine is the dense chokepoint corridor, the curve the sparse open flank.
// Mirror-symmetric across z=0 (the X axis) so the two halves are fair. The
// layout is GENERATED by tools/maps/build_douglas.mjs — edit that, not the JSON.
//
// ponytail: the *visuals* come from the baked glb; the colliders stay the
// proven cuboids. Same box list → they align. Re-run the Blender bake if the
// layout JSON changes, or render and collision drift apart.

import type { World } from '@dimforge/rapier3d-compat';
import { Quaternion, Vector3 } from 'three';
import { addStaticBox } from '../physics/world';
import data from '../../assets/maps/de_douglas.json';

// docs/art-direction.md palette (mirrors the hex colours in the JSON).
export const PALETTE = {
  concrete: 0xa5a29b,
  concreteDark: 0x5e5c58,
  sandstoneLight: 0xc9ae7c,
  wood: 0x7a5b3c,
} as const;

export interface MapBox {
  /** centre [x, y, z] */
  readonly c: readonly [number, number, number];
  /** full size [w, h, d] */
  readonly s: readonly [number, number, number];
  readonly color: number;
  /** optional yaw about Y (radians). Used by the curved wall segments of the D. */
  readonly ry?: number;
}

/** A straight ramp on the walkable surface, start → end (see addRamp in main). */
export interface MapRamp {
  readonly start: readonly [number, number, number];
  readonly end: readonly [number, number, number];
  readonly width: number;
  readonly thickness: number;
  readonly color: number;
}

// JSON infers number[] for the coord arrays; the layout guarantees length-3
// tuples, so assert the shape at the boundary (the T0 test guards the data).
export const MAP_BOXES = data.boxes as unknown as readonly MapBox[];
export const MAP_RAMPS = data.ramps as unknown as readonly MapRamp[];
export const T_SPAWN = data.spawns.T as unknown as readonly [number, number, number];
export const CT_SPAWN = data.spawns.CT as unknown as readonly [number, number, number];

/** One oriented cuboid — the shared shape behind every box and ramp. */
export interface MapCuboid {
  readonly center: Vector3;
  readonly halfExtents: Vector3;
  readonly quat: Quaternion;
}

/**
 * Every collider in the map as an oriented cuboid. Single source of truth for
 * collision geometry: the Rapier colliders (buildMapColliders) and the navmesh
 * triangle emitter (collisionTriangles) both derive from this, so physics and
 * nav can't silently diverge.
 */
export function mapCuboids(): MapCuboid[] {
  const out: MapCuboid[] = [];
  const up = new Vector3(0, 1, 0);
  for (const b of MAP_BOXES) {
    out.push({
      center: new Vector3(b.c[0], b.c[1], b.c[2]),
      halfExtents: new Vector3(b.s[0] / 2, b.s[1] / 2, b.s[2] / 2),
      quat: new Quaternion().setFromAxisAngle(up, b.ry ?? 0),
    });
  }
  for (const r of MAP_RAMPS) {
    const dir = new Vector3(r.end[0] - r.start[0], r.end[1] - r.start[1], r.end[2] - r.start[2]);
    const length = dir.length();
    const angle = Math.atan2(dir.y, dir.x);
    const normal = new Vector3(-Math.sin(angle), Math.cos(angle), 0);
    const center = new Vector3(r.start[0], r.start[1], r.start[2])
      .add(new Vector3(r.end[0], r.end[1], r.end[2]))
      .multiplyScalar(0.5)
      .addScaledVector(normal, -r.thickness / 2);
    out.push({
      center,
      halfExtents: new Vector3(length / 2, r.thickness / 2, r.width / 2),
      quat: new Quaternion().setFromAxisAngle(new Vector3(0, 0, 1), angle),
    });
  }
  return out;
}

/**
 * Build the greybox map's Rapier cuboid colliders into `world`. The engine
 * (main.ts) and the headless sim tests both call this, so collision is defined
 * in exactly one place. Visuals come from the baked glb; these stay the cuboids.
 */
export function buildMapColliders(world: World): void {
  for (const { center, halfExtents, quat } of mapCuboids()) {
    addStaticBox(world, center, halfExtents, quat);
  }
}

// Unit-cube corner offsets (±1 per axis) and the 12 triangles winding them CCW
// outward. Scaled by halfExtents, rotated by quat, offset by center below.
const CUBE_CORNERS: readonly [number, number, number][] = [
  [-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1],
  [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1],
];
const CUBE_TRIS: readonly number[] = [
  0, 2, 1, 0, 3, 2, // -z
  4, 5, 6, 4, 6, 7, // +z
  0, 1, 5, 0, 5, 4, // -y
  3, 7, 6, 3, 6, 2, // +y
  0, 4, 7, 0, 7, 3, // -x
  1, 2, 6, 1, 6, 5, // +x
];

/**
 * The whole map as a flat triangle soup (positions, indices) for the offline
 * recast navmesh bake. Derived from mapCuboids() so nav walks exactly what the
 * player collides with.
 */
export function collisionTriangles(): { positions: number[]; indices: number[] } {
  const positions: number[] = [];
  const indices: number[] = [];
  const v = new Vector3();
  for (const { center, halfExtents, quat } of mapCuboids()) {
    const base = positions.length / 3;
    for (const [cx, cy, cz] of CUBE_CORNERS) {
      v.set(cx * halfExtents.x, cy * halfExtents.y, cz * halfExtents.z)
        .applyQuaternion(quat)
        .add(center);
      positions.push(v.x, v.y, v.z);
    }
    for (const idx of CUBE_TRIS) indices.push(base + idx);
  }
  return { positions, indices };
}
