import { describe, expect, it } from 'vitest';
import {
  decodeBye,
  decodeCommand,
  decodeJoin,
  decodeSnapshot,
  decodeWelcome,
  encodeBye,
  encodeCommand,
  encodeJoin,
  encodeWelcome,
  F_ALIVE,
  F_DUCKED,
  F_TEAM_CT,
  PROTOCOL_VERSION,
  SPECTATOR,
  TAG_JOIN,
  type Snapshot,
  TAG_SNAP,
  TAG_WELCOME,
} from './protocol';

describe('protocol (TS)', () => {
  it('round-trips a Welcome', () => {
    const original = {
      yourSlot: 3, map: 'de_douglas', seed: 42, serverTick: 0,
      maxPlayers: 10, players: 5, spectators: 2, specCap: 7,
      roundsToWin: 16,
    };
    const encoded = encodeWelcome(original);
    const decoded = decodeWelcome(encoded);
    expect(decoded).toEqual(original);
  });

  it('round-trips spectator slot', () => {
    const original = {
      yourSlot: SPECTATOR, map: 'de_douglas', seed: 99, serverTick: 1234,
      maxPlayers: 10, players: 10, spectators: 3, specCap: 7,
      roundsToWin: 0,
    };
    const encoded = encodeWelcome(original);
    const decoded = decodeWelcome(encoded);
    expect(decoded).toEqual(original);
  });

  it('old-format Welcome (pre-Phase 9) still decodes', () => {
    // Encode with capacity fields, then snip them off.
    const full = encodeWelcome({
      yourSlot: 1, map: 'x', seed: 0, serverTick: 0,
      maxPlayers: 0, players: 0, spectators: 0, specCap: 0,
      roundsToWin: 0,
    });
    const old = new Uint8Array(full.buffer, 0, full.length - 5);
    const w = decodeWelcome(old);
    expect(w).not.toBeNull();
    expect(w!.maxPlayers).toBe(0);
    expect(w!.players).toBe(0);
    expect(w!.roundsToWin).toBe(0);
  });

  it('rejects wrong tag', () => {
    const buf = new Uint8Array(16);
    buf[0] = 99;
    buf[1] = PROTOCOL_VERSION;
    expect(decodeWelcome(buf)).toBeNull();
  });

  it('rejects wrong version', () => {
    const encoded = encodeWelcome({
      yourSlot: 0, map: 'x', seed: 0, serverTick: 0,
      maxPlayers: 0, players: 0, spectators: 0, specCap: 0,
      roundsToWin: 0,
    });
    encoded[1] = 99;
    expect(decodeWelcome(encoded)).toBeNull();
  });

  it('rejects too-short data', () => {
    expect(decodeWelcome(new Uint8Array(5))).toBeNull();
  });

  // Cross-compatibility: bytes generated by the Rust side for
  // Welcome { yourSlot: 0, map: "x", seed: 0, serverTick: 0, maxPlayers: 0, ..., roundsToWin: 0 }
  it('decodes bytes produced by the Rust encoder', () => {
    const buf = new Uint8Array(18);
    buf[0] = TAG_WELCOME;
    buf[1] = PROTOCOL_VERSION;
    buf[2] = 0;
    buf[3] = 1;
    buf[4] = 0x78;
    const decoded = decodeWelcome(buf);
    expect(decoded).toEqual({
      yourSlot: 0,
      map: 'x',
      seed: 0,
      serverTick: 0,
      maxPlayers: 0,
      players: 0,
      spectators: 0,
      specCap: 0,
      roundsToWin: 0,
    });
  });

  // --------------- Join / Bye (Phase 9) ---------------

  it('round-trips Join messages (T, CT, spec)', () => {
    for (const t of [0, 1, 2]) {
      expect(decodeJoin(encodeJoin({ team: t }))).toEqual({ team: t });
    }
  });

  it('round-trips Join with a token (Phase 17.4)', () => {
    const j = decodeJoin(encodeJoin({ team: 1, token: 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMTIzIn0.signature' }));
    expect(j).not.toBeNull();
    expect(j!.team).toBe(1);
    expect(j!.token).toBe('eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMTIzIn0.signature');
  });

  it('round-trips Join with a picked name (Phase 21)', () => {
    const j = decodeJoin(encodeJoin({ team: 0, token: 'tok', name: 'Dougy' }));
    expect(j).toMatchObject({ team: 0, token: 'tok', name: 'Dougy' });
  });

  it('round-trips Join with a name but no token', () => {
    const j = decodeJoin(encodeJoin({ team: 1, name: 'guest' }));
    expect(j).toMatchObject({ team: 1, name: 'guest' });
    expect(j!.token).toBeUndefined();
  });

  it('decodes old 3-byte Join format (backwards compat)', () => {
    const buf = new Uint8Array([TAG_JOIN, PROTOCOL_VERSION, 1]);
    expect(decodeJoin(buf)).toEqual({ team: 1 });
  });

  it('decodes new 5-byte Join with no token', () => {
    const buf = new Uint8Array([TAG_JOIN, PROTOCOL_VERSION, 0, 0, 0]);
    expect(decodeJoin(buf)).toEqual({ team: 0 });
  });

  it('rejects Join with wrong tag', () => {
    const buf = new Uint8Array([99, PROTOCOL_VERSION, 0]);
    expect(decodeJoin(buf)).toBeNull();
  });

  it('rejects truncated Join', () => {
    const buf = new Uint8Array([TAG_JOIN, PROTOCOL_VERSION]);
    expect(decodeJoin(buf)).toBeNull();
  });

  it('round-trips a Bye', () => {
    const b = { reason: 'full' };
    expect(decodeBye(encodeBye(b))).toEqual(b);
  });

  it('round-trips an empty-reason Bye', () => {
    expect(decodeBye(encodeBye({ reason: '' }))).toEqual({ reason: '' });
  });

  it('rejects Bye with wrong tag', () => {
    const buf = new Uint8Array([99, PROTOCOL_VERSION, 1, 102]);
    expect(decodeBye(buf)).toBeNull();
  });

  it('round-trips a CommandFrame without a shot', () => {
    const c = {
      seq: 12345,
      lastAckSnapshot: 678,
      buttons: 0b1010_0101,
      yaw: 1.25,
      pitch: -0.5,
      weapon: 2,
      shot: null,
    };
    expect(decodeCommand(encodeCommand(c))).toEqual(c);
  });

  it('round-trips a CommandFrame with a shot', () => {
    const c = {
      seq: 1,
      lastAckSnapshot: 0,
      buttons: 0,
      yaw: 3,
      pitch: 0.5,
      weapon: 1,
      shot: { eyePos: [1, 1.5, -25] as [number, number, number], dir: [0, 0, 1] as [number, number, number] },
    };
    expect(decodeCommand(encodeCommand(c))).toEqual(c);
  });

  // Golden bytes shared with sim/src/protocol.rs snapshot_golden_bytes.
  it('decodes a Snapshot produced by the Rust encoder', () => {
    // Tag(1) + Version(1) + tick(4) + ack(4) + entityCount(1)
    //   + entity(36) + eventCount(1) + round(9: phase+time_left_ms.u32+scoreT+scoreCt) = 59
    const bytes = new Uint8Array([
      3, 1, 100, 0, 0, 0, 7, 0, 0, 0, 1, 0, 5, 0, 0, 192, 63, 0, 0, 0, 0, 0, 0, 200, 193, 0, 0,
      128, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 63, 0, 0, 128, 190, 100, 0, 1, 30,
      2, 0, 3, 0, 3, 67, 84, 49, // kills=2, deaths=3, nameLen=3, "CT1"
      0, 1, 96,
      234, 0, 0, 2, 0, 3, 0,
    ]);
    const expected: Snapshot = {
      serverTick: 100,
      ackSeq: 7,
      entities: [
        {
          slot: 0,
          flags: F_ALIVE | F_TEAM_CT,
          pos: [1.5, 0, -25],
          vel: [4, 0, 0],
          yaw: 1.5,
          pitch: -0.25,
          health: 100,
          armor: 0,
          weapon: 1,
          ammo: 30,
          kills: 2,
          deaths: 3,
          name: 'CT1',
        },
      ],
      events: [],
      round: { phase: 1, timeLeftMs: 60000, scoreT: 2, scoreCt: 3 },
    };
    expect(decodeSnapshot(bytes)).toEqual(expected);
  });

  it('rejects a Snapshot with the wrong tag', () => {
    const buf = new Uint8Array(11);
    buf[0] = 99;
    buf[1] = PROTOCOL_VERSION;
    expect(decodeSnapshot(buf)).toBeNull();
    // sanity: a well-formed empty-entity snapshot header decodes
    const ok = new Uint8Array(21);
    ok[0] = TAG_SNAP;
    ok[1] = PROTOCOL_VERSION;
    expect(decodeSnapshot(ok)).not.toBeNull();
    expect(F_DUCKED).toBe(2);
  });
});
