import { describe, expect, it } from 'vitest';
import {
  decodeCommand,
  decodeSnapshot,
  decodeWelcome,
  encodeCommand,
  encodeWelcome,
  F_ALIVE,
  F_DUCKED,
  F_TEAM_CT,
  PROTOCOL_VERSION,
  SPECTATOR,
  type Snapshot,
  TAG_SNAP,
  TAG_WELCOME,
} from './protocol';

describe('protocol (TS)', () => {
  it('round-trips a Welcome', () => {
    const original = { yourSlot: 3, map: 'de_douglas', seed: 42, serverTick: 0 };
    const encoded = encodeWelcome(original);
    const decoded = decodeWelcome(encoded);
    expect(decoded).toEqual(original);
  });

  it('round-trips spectator slot', () => {
    const original = { yourSlot: SPECTATOR, map: 'de_douglas', seed: 99, serverTick: 1234 };
    const encoded = encodeWelcome(original);
    const decoded = decodeWelcome(encoded);
    expect(decoded).toEqual(original);
  });

  it('rejects wrong tag', () => {
    const buf = new Uint8Array(12);
    buf[0] = 99; // not TAG_WELCOME
    buf[1] = PROTOCOL_VERSION;
    expect(decodeWelcome(buf)).toBeNull();
  });

  it('rejects wrong version', () => {
    const encoded = encodeWelcome({ yourSlot: 0, map: 'x', seed: 0, serverTick: 0 });
    encoded[1] = 99;
    expect(decodeWelcome(encoded)).toBeNull();
  });

  it('rejects too-short data', () => {
    expect(decodeWelcome(new Uint8Array(5))).toBeNull();
  });

  // Cross-compatibility: bytes generated by the Rust side for
  // Welcome { yourSlot: 0, map: "x", seed: 0, serverTick: 0 }
  it('decodes bytes produced by the Rust encoder', () => {
    // Tag(1) + Version(1) + yourSlot(1) + mapLen(1) + "x"(1) + seed(4) + tick(4) = 13
    const buf = new Uint8Array(13);
    buf[0] = TAG_WELCOME;
    buf[1] = PROTOCOL_VERSION;
    buf[2] = 0;
    buf[3] = 1;
    buf[4] = 0x78; // 'x'
    // bytes 5-8: seed = 0
    // bytes 9-12: serverTick = 0
    const decoded = decodeWelcome(buf);
    expect(decoded).toEqual({
      yourSlot: 0,
      map: 'x',
      seed: 0,
      serverTick: 0,
    });
  });

  it('round-trips a CommandFrame without a shot', () => {
    const c = {
      seq: 12345,
      lastAckSnapshot: 678,
      buttons: 0b1010_0101,
      yaw: 1.25,
      pitch: -0.5,
      weapon: 2,
      shot: null,
    };
    expect(decodeCommand(encodeCommand(c))).toEqual(c);
  });

  it('round-trips a CommandFrame with a shot', () => {
    const c = {
      seq: 1,
      lastAckSnapshot: 0,
      buttons: 0,
      yaw: 3,
      pitch: 0.5,
      weapon: 1,
      shot: { eyePos: [1, 1.5, -25] as [number, number, number], dir: [0, 0, 1] as [number, number, number] },
    };
    expect(decodeCommand(encodeCommand(c))).toEqual(c);
  });

  // Golden bytes shared with sim/src/protocol.rs snapshot_golden_bytes.
  // The new format adds an events count byte (0x00) between entities and round.
  it('decodes a Snapshot produced by the Rust encoder', () => {
    const bytes = new Uint8Array([
      3, 1, 100, 0, 0, 0, 7, 0, 0, 0, 1, 0, 5, 0, 0, 192, 63, 0, 0, 0, 0, 0, 0, 200, 193, 0, 0,
      128, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 63, 0, 0, 128, 190, 100, 0, 1, 30, 0, 1, 96,
      234, 2, 0, 3, 0,
    ]);
    const expected: Snapshot = {
      serverTick: 100,
      ackSeq: 7,
      entities: [
        {
          slot: 0,
          flags: F_ALIVE | F_TEAM_CT,
          pos: [1.5, 0, -25],
          vel: [4, 0, 0],
          yaw: 1.5,
          pitch: -0.25,
          health: 100,
          armor: 0,
          weapon: 1,
          ammo: 30,
        },
      ],
      events: [],
      round: { phase: 1, timeLeftMs: 60000, scoreT: 2, scoreCt: 3 },
    };
    expect(decodeSnapshot(bytes)).toEqual(expected);
  });

  it('rejects a Snapshot with the wrong tag', () => {
    const buf = new Uint8Array(11);
    buf[0] = 99;
    buf[1] = PROTOCOL_VERSION;
    expect(decodeSnapshot(buf)).toBeNull();
    // sanity: a well-formed empty-entity snapshot header decodes
    const ok = new Uint8Array(20);
    ok[0] = TAG_SNAP;
    ok[1] = PROTOCOL_VERSION;
    expect(decodeSnapshot(ok)).not.toBeNull();
    expect(F_DUCKED).toBe(2);
  });
});
