import { describe, expect, it } from 'vitest';
import {
  decodeWelcome,
  encodeWelcome,
  PROTOCOL_VERSION,
  SPECTATOR,
  TAG_WELCOME,
} from './protocol';

describe('protocol (TS)', () => {
  it('round-trips a Welcome', () => {
    const original = { yourSlot: 3, map: 'de_douglas', seed: 42, serverTick: 0 };
    const encoded = encodeWelcome(original);
    const decoded = decodeWelcome(encoded);
    expect(decoded).toEqual(original);
  });

  it('round-trips spectator slot', () => {
    const original = { yourSlot: SPECTATOR, map: 'de_douglas', seed: 99, serverTick: 1234 };
    const encoded = encodeWelcome(original);
    const decoded = decodeWelcome(encoded);
    expect(decoded).toEqual(original);
  });

  it('rejects wrong tag', () => {
    const buf = new Uint8Array(12);
    buf[0] = 99; // not TAG_WELCOME
    buf[1] = PROTOCOL_VERSION;
    expect(decodeWelcome(buf)).toBeNull();
  });

  it('rejects wrong version', () => {
    const encoded = encodeWelcome({ yourSlot: 0, map: 'x', seed: 0, serverTick: 0 });
    encoded[1] = 99;
    expect(decodeWelcome(encoded)).toBeNull();
  });

  it('rejects too-short data', () => {
    expect(decodeWelcome(new Uint8Array(5))).toBeNull();
  });

  // Cross-compatibility: bytes generated by the Rust side for
  // Welcome { yourSlot: 0, map: "x", seed: 0, serverTick: 0 }
  it('decodes bytes produced by the Rust encoder', () => {
    // Tag(1) + Version(1) + yourSlot(1) + mapLen(1) + "x"(1) + seed(4) + tick(4) = 13
    const buf = new Uint8Array(13);
    buf[0] = TAG_WELCOME;
    buf[1] = PROTOCOL_VERSION;
    buf[2] = 0;
    buf[3] = 1;
    buf[4] = 0x78; // 'x'
    // bytes 5-8: seed = 0
    // bytes 9-12: serverTick = 0
    const decoded = decodeWelcome(buf);
    expect(decoded).toEqual({
      yourSlot: 0,
      map: 'x',
      seed: 0,
      serverTick: 0,
    });
  });
});
